/A2/physics/Physics QGSP_BIC

/run/initialize


/control/verbose 2
/control/saveHistory
/run/verbose 2

#/vis/scene/create
##/vis/open OGLSX
/vis/open DAWNFILE
#
/vis/drawVolume
##/vis/viewer/set/viewpointThetaPhi 45. 45.
##/vis/viewer/set/viewpointThetaPhi 25. 90.
#/vis/viewer/set/viewpointThetaPhi 90. 0.
#/vis/viewer/set/style surface
##/vis/viewer/set/style w
#/vis/viewer/zoom 3
#/vis/viewer/panTo -1
#/vis/scene/add/axes 0 0 0 139 cm
/vis/viewer/flush
/vis/viewer/rebuild

#/tracking/storeTrajectory 1
###/vis/scene/endOfEventAction accumulate
###
#/gun/particle neutron
#/gun/energy 100 MeV
##/gun/position 0 0 0.3 m
#/gun/direction 0 1 1
###
#/run/verbose      2
#/event/verbose    1
#/tracking/verbose 2
#/run/beamOn 1


/particle/select kaon0S
/particle/property/decay/select 0
/particle/property/decay/br 0
/particle/property/decay/select 1
/particle/property/decay/br 1
/particle/property/decay/dump


/particle/select lambda
/particle/property/decay/select 0
/particle/property/decay/br 1
/particle/property/decay/select 1
/particle/property/decay/br 0
/particle/property/decay/dump

/particle/select pi0
/particle/property/decay/dump
