/A2/physics/Physics QGSP_BIC

/run/initialize


/control/verbose 2
/control/saveHistory
/run/verbose 2

/vis/scene/create

/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate

/vis/open OGLIX
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/viewer/set/style surface
/tracking/storeTrajectory 1	

/gun/particle proton
/gun/energy 100 MeV

#for checking CCUT
#/gun/direction 0. 10. 22

#for checking CNIN
/gun/direction 1 0 0

/gun/position 0 0 0

